server :
  port : 8090
spring :
  application :
    name : tuGraph
  datasource:
    url: jdbc:mysql://localhost:3306/tugraph?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ggpp1993
    driver-class-name: com.mysql.cj.jdbc.Driver
  neo4j:
    uri: bolt://localhost:7687
    username: neo4j
    password: GGpp1993@
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl